# -------------------- SpringBoot配置
server:
  port: 8081

# -------------------- 自定义属性

# --------------------

# -------------------- 自定义上传文件夹
upload:
  location: D:/springboot/
  locationImg: D:/springboot/img

# -------------------- spring配置
spring:
# -------------------- jdbc配置
  datasource:
    url: jdbc:mysql:///springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
# -------------------- Redis配置
  redis:
    host: localhost
    port: 6379
    timeout: 30000
    jedis:
      pool:
        max-active: 8
        max-idle: 5
        min-idle: 1
# -------------------- 静态资源配置
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/public/, classpath:/static/, file:${upload.location}/
      chain:
        strategy:
          content:
            enabled: true # 内容版本管理策略会给静态文件添加随机hash值
            paths: /**
# -------------------- 文件上传配置
  servlet:
    multipart:
      location:
      max-file-size: 1GB
      max-request-size: 1GB
# -------------------- Thymeleaf模板引擎配置
  thymeleaf:
    cache: false # 缓存HTML模板，开发环境中必须使用false，部署环境使用true
# -------------------- Spring Security认证配置
  #配置security登录验证
  security:
    user:
      password: 123
      name: admin
    oauth2:
      client:
        registration:
          #          github:
          #            client-id: ${clientId}
          #            client-secret: ${clientSecret}
          #            redirect-uri: '{baseUrl}/login/oauth2/{registrationId}'
          #            client-authentication-method: POST
          #            scope: read:user
          #            client-name: GitHub
          gitee:
            provider: gitee
            client-id: 2694c10f42c9d33d9257e5693bcd5183506ee62e5b00396e13e8e5b80d882048
            client-secret: 6d046cc842f9e1924566d1c16e46350f4968354a98f339784ef6395bd6577f4d
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/gitee
            client-authentication-method: POST
            scope: user_info
            client-name: Gitee
        provider:
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-name-attribute: id
            user-info-uri: https://gitee.com/api/v5/user
    #          github:
    #            authorization-uri: https://github.com/login/oauth/authorize
    #            token-uri: https://github.com/login/oauth/access_token
    #            user-name-attribute: id
    #            user-info-uri: https://api.github.com/user



# -------------------- JPA配置
#  jpa:
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#    show-sql: true
#    generate-ddl: true

# -------------------- Mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml

# -------------------- Mybatis-plus的配置
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.zking.entity
  configuration:
    map-underscore-to-camel-case: true

# -------------------- 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  auto-dialect: true

# -------------------- Log日志配置
logging:
  level:
    root: info
    com.zking: info
  file.path: .
  file.name: target\log.log


#支付
# -------------------- 自定义上支付宝沙箱参数
alipay:
  url: https://openapi.alipaydev.com/gateway.do
  appid: 2021000121622532
  appidLs: 2021000119653835
  privateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCjF/fKPGBZ5mTY+uxl/6eQE/9vnNvXaSdfWeZn2Szm9x/XN68RMVV6mkpiJXYkJDdkR1FouyxFMvbHoqrZNgEuKF//DHJabxPKFpT26FahSEuJeYPXL3UwFh4IUFpYOz/IHCT54w8mh/mx5Qp1MkWvawcTZ2SIgXLr5kb2PE4U4NuCC7ptc4bBDIog9nFgoKvDteFrBfGowBQU/EUIUMNxIGr9Vk3jEUgFCcbVf+B7igekWLGCZugjuK/aG11XAD+Og5eBrw+WwgsweEX4HlNURZiA3ZeV7LliISXcHFmX/UquuI5dPc65W6bcCCVn3cr0taReoprx7D563xSLl0UFAgMBAAECggEBAJzT0E8krZXk6LaI2sbeBheSUz7VO8Swdc7HmLnlaLsTiQefoPVMViDVuo8T7L2mIamItqyZx2EnN4wSTG0f9BSZeG29Xzy8sO/TtRyTn7Ho3dHtCizikrJRokFmWuma16MqBRhREWGAwUchsmOtmrqqlRxAgLiOmZ5jSXs/0+lYIgbU1Qc/jVairJ3t03X4Q+QSdOen0kKTqJ7+H6yCf2GriZWFy3HHV8eMtGdadex6AgXBaTwdDlqnhAZ6Jp7XNx0bLkT0Q1Blq8/R0luWClWk914aKIL6QfEfRU+k8evRiQxzKx5emVfwIDDKeAGP6QhGC3O65x44PtkjXELqPSUCgYEA1UfJ8Zfsu/9fEA93jPxBXmK2qHwTg/Mcz3Z9drsCGCDTf+V3XYCuqDWd/nRRjEnJNonxG/UutIWHqC6OHETVj4KY55TapTeiaQ9tq65ZKIIfayNCTAhY1Vu6pBAQEbc+1P0vM87XnimWBhU+FKWUhscGyu6uxsxCMOpacgO2kJMCgYEAw8LKU3Rd73dsZOv6lSFE0BKliB1Y6Wl8oYp0AXKJi0gyUlbulDBX0gdGdXTRiqEE2ot41SX62v4dRsX+Cumw5JpUm/qVGZUkxnnqzGkrffXlVt2Q3m2E6+26um3xy+s16Ub5acJWHtsnUBaKh0NkvK0974qAgnqTjDl1dOXxCwcCgYEAiREX4WHnzHI0H9gw1rSPNh9ukB0dVaF6FIJr41AP6n2+LuXDrp2yoXvDy/HpLqWE4L4J7BPILk/afOVegyBht1cQ+VOaqK92etplev4TYostseb5BnAe1w+ahTGlgh0oDi2glkUKISVMuyAPw6keKPfjj6uRO0WuDE2wTrHANG0CgYEApfosLaIGWxj4UIE7zuGMRJbqvoOTdSO5RgXr4aZJNEycTe/jDMYIT81XUhMf7tgjE2EZrC8tiCvYir8oa/xDvS+U+UL209/+dEG+cF3jQEMSlhn50H0vLBI+Nf8t+eWNqiJBKghZmIPbyy2xeooLiWWhk83ss7RWEZhOHDUxsFUCgYBIoxG6b4yU1zlno5sduAMnC7WIcygT2DU44BQY5GU9UKbk1x54PVtAcOgob5wm/iUwURe5Y9dEfM6Ld793QctGiPyhI7O9AQWoqJvDMtAQgh9lCC6aTqWA+QvODEjzNGv3XIBXBI+CvUxOMtzj41daeS6X/Kg/FW6mVC3olSucfw==
  privateLSKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCNie/qLWRKIwzHTMVNWIVf6Rw0KQ7Z+GnG6OUutb3PsM6GVBmYueKFjQYJ10Kd2K7GTtuI5uJta3e2U1A1g2l0l2bJgfy6DBLYQnf7zSdc4/d1UhvrDmXZIKXjGnMbt8FnMscbMVhJpWJH7cAGvM+rZGFJbv5F3etwLJiD0Ah46JRRDe5tlccZSG7upvpOieFWYeh/lqV46v8OcTiiemr7262It6gWUVtNtvCK90ssMMM1pF5ho6GJoPG0WEC4v56oZw/qtVu8oKLuIYnA3U5PbOAZxL0W7KhO6Miy+g02X/eFoIFyp6mtbhgVxACtOUo/blD5elQ94fIU9/xwDHotAgMBAAECggEBAIsl5tXE1moEV1XAZeCKfGU0WeP10YH9NJC2+kmXpwn+equZFqkNZmOBp0QZeoaQNhMEB9RpmIWWN9Tpx1s03IIhLo5A2uNVZ1lwz2Cf6mjqPaf7lzLZrstty2if4jaHyv3X7+MN+gw9KYgpdrWo/kkzoGl/U0AA0qwvS6ma5hlmmussZLrS6YqC5+bNEiTkEPJ9Y0YeqqcaY5L9xeg4ocwAa8nciax9eptfWEuSYBb7Ut3IAFRmqjgtA1pjX1PPHwyy/K3fQeLKZjrsMSq5t0jRWXCDmqR3CG7EnUNo2VH3pU1mQnTTxe2Rl6B+kOy0L+GqGQ6g3p4nxeU6vWsDgEECgYEA91L5c/qUujgWS+11FiMlYQfA0oV8LDoYRfIbE097MBNKjO47MCnldwrlj4lQAL2fGyiotjP3AwZuW1FRIX5+FljagGglVnhFIOdtQpZdjW9czfLVjpgDbCNsvUVBYg85dkoHkoOIdPsmdDjGE3IlsMGdfHU0XuMzXzNxMeN9rTUCgYEAkoD8ue4K+WOQ7iEMidk3QwVL7lFBDSQB0/DfA73qndVRwQVBa0bBAN+UsSb97xic4rdUvvWxximohFm0HOL18N94TqFnU7Mp8Nw4T3+UckPozkG99KsCEpP+gw6HSxtithLXSnuNrz5hZfNspirKH3bEZhZ1mfC4ZUNxLorOUBkCgYEAwfZjxi4917FG4zMOAVd86BTRhwjCsli5Upml3EYYIULv04i+CG7DE9IK6L/Sa1JK5lzDu2kTjl7Ly3gBfZgbQGFcsxl6Ns9Jv51f1bnhEpvEl4ubKiJThMpfbCxVM5cnBHrYZ3IaYUvaA4nG5dc+cdnWLZYphUT/s+i/HFYB6QUCgYAnEitUUr2ugPU37KxxXvKz9wenCRh2LrImGckAMHgPm8Jv3bzypS3306jODf4O89tzQz1gqBm/JYEBuwKj6Yt5r79gCP+LfO6kg7aozPeD+cRurW3BgJHO7pUj0o4WY7lRoXi1Lno80EAddmv1bNf2yC/cogS/B0nGB9R5ex9GkQKBgQDnEIyTTOa5I1WHBoA31/0UrWuKpF9nkz8TfJuZFvuHUz4dDuWC2NRK170lm/iyqIg+8MZLVphf0e0h/Tim4op4f/bDEO1+WYQT+vIGna5Ptcpd0+Gzm4vl7CQ6fwNuwovxQ1gYiPwU094/ZpzREdpiyWu3RBqWRv7pJQrXywGulA==\", \"json\", \"utf-8\", \"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxcb7665b27YnKEvHF1PwjmhFWWldMLXwOQ56mRnMQCD2QM4BAPiofkobvr+9iL1l8BO/8Oy/k/Ap6s1usB3YRfJGQnReGIiQxiZNjqCoUl6AFK2gxKbZFF7wbwYM/pB9kENvWuN1Uu5vm0oUQO2i29PHAAQwMxkSgO18eEzNIiWNOoEfrFz17bzIK1heD5QtlA59IWI0aSlhIkJLx5hWOmOuQUsQ59I88ZsEM5Zb1YNymLZM7zjnbmSKT44Bg3+evnXLYc/byBCvPXVJmxRiNFS14myi7LrCd+j4r7Zp48NLhsPzcDzYRt+2MHMmz1vmWKicANAuHiK9agCd4QDOvwIDAQAB
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0j5BOg0Zg78IZ6WRgKRXNaJqAIjZZlJEKMPSYfNbvuJS/jmykIX1/QK3ZMTBWVr3sKP9ApgLNw9q6Ft+uIzL1UQALi4ri5RF90uHXcMGECjEQUTL2lANJqlAfov1MRMb6fQNzNSJv3F5aKDI/e4c63FGMF3CiePzZLIEgSudy2BTHcl06AtpQsTeLxlcvUuwin8Uvzx+qtFoWDqWBVqMkVLDEh2WUvvMncUphNdEzICw734ID9c7NNTr9yzN/8LAPqNF4emhYS5JtcVUuxqlQoW4sq/s4wMa2FOuEQYNo8vBj1LGbsxvPcJevLcZiAgMfP6yLJQU6PWBgvJbsb/SOwIDAQAB
  publicLSKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxcb7665b27YnKEvHF1PwjmhFWWldMLXwOQ56mRnMQCD2QM4BAPiofkobvr+9iL1l8BO/8Oy/k/Ap6s1usB3YRfJGQnReGIiQxiZNjqCoUl6AFK2gxKbZFF7wbwYM/pB9kENvWuN1Uu5vm0oUQO2i29PHAAQwMxkSgO18eEzNIiWNOoEfrFz17bzIK1heD5QtlA59IWI0aSlhIkJLx5hWOmOuQUsQ59I88ZsEM5Zb1YNymLZM7zjnbmSKT44Bg3+evnXLYc/byBCvPXVJmxRiNFS14myi7LrCd+j4r7Zp48NLhsPzcDzYRt+2MHMmz1vmWKicANAuHiK9agCd4QDOvwIDAQAB
  notifyUrl: http://localhost:8081/notify # 异步请求成的地址
  returnUrl: http://localhost:8081/vip/alipayReturn # 同步请求成功之后返回的地址
  # notifyUrl和returnUrl不能加?id=123这类自定义参数，必须外网可以正常访问

# 自定义属性
#alipay:
#  url: https://openapi.alipaydev.com/gateway.do
#  appid: 2021000121622532
#  appidLs: 2021000119653835
#  privateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCjF/fKPGBZ5mTY+uxl/6eQE/9vnNvXaSdfWeZn2Szm9x/XN68RMVV6mkpiJXYkJDdkR1FouyxFMvbHoqrZNgEuKF//DHJabxPKFpT26FahSEuJeYPXL3UwFh4IUFpYOz/IHCT54w8mh/mx5Qp1MkWvawcTZ2SIgXLr5kb2PE4U4NuCC7ptc4bBDIog9nFgoKvDteFrBfGowBQU/EUIUMNxIGr9Vk3jEUgFCcbVf+B7igekWLGCZugjuK/aG11XAD+Og5eBrw+WwgsweEX4HlNURZiA3ZeV7LliISXcHFmX/UquuI5dPc65W6bcCCVn3cr0taReoprx7D563xSLl0UFAgMBAAECggEBAJzT0E8krZXk6LaI2sbeBheSUz7VO8Swdc7HmLnlaLsTiQefoPVMViDVuo8T7L2mIamItqyZx2EnN4wSTG0f9BSZeG29Xzy8sO/TtRyTn7Ho3dHtCizikrJRokFmWuma16MqBRhREWGAwUchsmOtmrqqlRxAgLiOmZ5jSXs/0+lYIgbU1Qc/jVairJ3t03X4Q+QSdOen0kKTqJ7+H6yCf2GriZWFy3HHV8eMtGdadex6AgXBaTwdDlqnhAZ6Jp7XNx0bLkT0Q1Blq8/R0luWClWk914aKIL6QfEfRU+k8evRiQxzKx5emVfwIDDKeAGP6QhGC3O65x44PtkjXELqPSUCgYEA1UfJ8Zfsu/9fEA93jPxBXmK2qHwTg/Mcz3Z9drsCGCDTf+V3XYCuqDWd/nRRjEnJNonxG/UutIWHqC6OHETVj4KY55TapTeiaQ9tq65ZKIIfayNCTAhY1Vu6pBAQEbc+1P0vM87XnimWBhU+FKWUhscGyu6uxsxCMOpacgO2kJMCgYEAw8LKU3Rd73dsZOv6lSFE0BKliB1Y6Wl8oYp0AXKJi0gyUlbulDBX0gdGdXTRiqEE2ot41SX62v4dRsX+Cumw5JpUm/qVGZUkxnnqzGkrffXlVt2Q3m2E6+26um3xy+s16Ub5acJWHtsnUBaKh0NkvK0974qAgnqTjDl1dOXxCwcCgYEAiREX4WHnzHI0H9gw1rSPNh9ukB0dVaF6FIJr41AP6n2+LuXDrp2yoXvDy/HpLqWE4L4J7BPILk/afOVegyBht1cQ+VOaqK92etplev4TYostseb5BnAe1w+ahTGlgh0oDi2glkUKISVMuyAPw6keKPfjj6uRO0WuDE2wTrHANG0CgYEApfosLaIGWxj4UIE7zuGMRJbqvoOTdSO5RgXr4aZJNEycTe/jDMYIT81XUhMf7tgjE2EZrC8tiCvYir8oa/xDvS+U+UL209/+dEG+cF3jQEMSlhn50H0vLBI+Nf8t+eWNqiJBKghZmIPbyy2xeooLiWWhk83ss7RWEZhOHDUxsFUCgYBIoxG6b4yU1zlno5sduAMnC7WIcygT2DU44BQY5GU9UKbk1x54PVtAcOgob5wm/iUwURe5Y9dEfM6Ld793QctGiPyhI7O9AQWoqJvDMtAQgh9lCC6aTqWA+QvODEjzNGv3XIBXBI+CvUxOMtzj41daeS6X/Kg/FW6mVC3olSucfw==
#  privateLSKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCNie/qLWRKIwzHTMVNWIVf6Rw0KQ7Z+GnG6OUutb3PsM6GVBmYueKFjQYJ10Kd2K7GTtuI5uJta3e2U1A1g2l0l2bJgfy6DBLYQnf7zSdc4/d1UhvrDmXZIKXjGnMbt8FnMscbMVhJpWJH7cAGvM+rZGFJbv5F3etwLJiD0Ah46JRRDe5tlccZSG7upvpOieFWYeh/lqV46v8OcTiiemr7262It6gWUVtNtvCK90ssMMM1pF5ho6GJoPG0WEC4v56oZw/qtVu8oKLuIYnA3U5PbOAZxL0W7KhO6Miy+g02X/eFoIFyp6mtbhgVxACtOUo/blD5elQ94fIU9/xwDHotAgMBAAECggEBAIsl5tXE1moEV1XAZeCKfGU0WeP10YH9NJC2+kmXpwn+equZFqkNZmOBp0QZeoaQNhMEB9RpmIWWN9Tpx1s03IIhLo5A2uNVZ1lwz2Cf6mjqPaf7lzLZrstty2if4jaHyv3X7+MN+gw9KYgpdrWo/kkzoGl/U0AA0qwvS6ma5hlmmussZLrS6YqC5+bNEiTkEPJ9Y0YeqqcaY5L9xeg4ocwAa8nciax9eptfWEuSYBb7Ut3IAFRmqjgtA1pjX1PPHwyy/K3fQeLKZjrsMSq5t0jRWXCDmqR3CG7EnUNo2VH3pU1mQnTTxe2Rl6B+kOy0L+GqGQ6g3p4nxeU6vWsDgEECgYEA91L5c/qUujgWS+11FiMlYQfA0oV8LDoYRfIbE097MBNKjO47MCnldwrlj4lQAL2fGyiotjP3AwZuW1FRIX5+FljagGglVnhFIOdtQpZdjW9czfLVjpgDbCNsvUVBYg85dkoHkoOIdPsmdDjGE3IlsMGdfHU0XuMzXzNxMeN9rTUCgYEAkoD8ue4K+WOQ7iEMidk3QwVL7lFBDSQB0/DfA73qndVRwQVBa0bBAN+UsSb97xic4rdUvvWxximohFm0HOL18N94TqFnU7Mp8Nw4T3+UckPozkG99KsCEpP+gw6HSxtithLXSnuNrz5hZfNspirKH3bEZhZ1mfC4ZUNxLorOUBkCgYEAwfZjxi4917FG4zMOAVd86BTRhwjCsli5Upml3EYYIULv04i+CG7DE9IK6L/Sa1JK5lzDu2kTjl7Ly3gBfZgbQGFcsxl6Ns9Jv51f1bnhEpvEl4ubKiJThMpfbCxVM5cnBHrYZ3IaYUvaA4nG5dc+cdnWLZYphUT/s+i/HFYB6QUCgYAnEitUUr2ugPU37KxxXvKz9wenCRh2LrImGckAMHgPm8Jv3bzypS3306jODf4O89tzQz1gqBm/JYEBuwKj6Yt5r79gCP+LfO6kg7aozPeD+cRurW3BgJHO7pUj0o4WY7lRoXi1Lno80EAddmv1bNf2yC/cogS/B0nGB9R5ex9GkQKBgQDnEIyTTOa5I1WHBoA31/0UrWuKpF9nkz8TfJuZFvuHUz4dDuWC2NRK170lm/iyqIg+8MZLVphf0e0h/Tim4op4f/bDEO1+WYQT+vIGna5Ptcpd0+Gzm4vl7CQ6fwNuwovxQ1gYiPwU094/ZpzREdpiyWu3RBqWRv7pJQrXywGulA==\", \"json\", \"utf-8\", \"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxcb7665b27YnKEvHF1PwjmhFWWldMLXwOQ56mRnMQCD2QM4BAPiofkobvr+9iL1l8BO/8Oy/k/Ap6s1usB3YRfJGQnReGIiQxiZNjqCoUl6AFK2gxKbZFF7wbwYM/pB9kENvWuN1Uu5vm0oUQO2i29PHAAQwMxkSgO18eEzNIiWNOoEfrFz17bzIK1heD5QtlA59IWI0aSlhIkJLx5hWOmOuQUsQ59I88ZsEM5Zb1YNymLZM7zjnbmSKT44Bg3+evnXLYc/byBCvPXVJmxRiNFS14myi7LrCd+j4r7Zp48NLhsPzcDzYRt+2MHMmz1vmWKicANAuHiK9agCd4QDOvwIDAQAB
#  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0j5BOg0Zg78IZ6WRgKRXNaJqAIjZZlJEKMPSYfNbvuJS/jmykIX1/QK3ZMTBWVr3sKP9ApgLNw9q6Ft+uIzL1UQALi4ri5RF90uHXcMGECjEQUTL2lANJqlAfov1MRMb6fQNzNSJv3F5aKDI/e4c63FGMF3CiePzZLIEgSudy2BTHcl06AtpQsTeLxlcvUuwin8Uvzx+qtFoWDqWBVqMkVLDEh2WUvvMncUphNdEzICw734ID9c7NNTr9yzN/8LAPqNF4emhYS5JtcVUuxqlQoW4sq/s4wMa2FOuEQYNo8vBj1LGbsxvPcJevLcZiAgMfP6yLJQU6PWBgvJbsb/SOwIDAQAB
#  publicLSKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxcb7665b27YnKEvHF1PwjmhFWWldMLXwOQ56mRnMQCD2QM4BAPiofkobvr+9iL1l8BO/8Oy/k/Ap6s1usB3YRfJGQnReGIiQxiZNjqCoUl6AFK2gxKbZFF7wbwYM/pB9kENvWuN1Uu5vm0oUQO2i29PHAAQwMxkSgO18eEzNIiWNOoEfrFz17bzIK1heD5QtlA59IWI0aSlhIkJLx5hWOmOuQUsQ59I88ZsEM5Zb1YNymLZM7zjnbmSKT44Bg3+evnXLYc/byBCvPXVJmxRiNFS14myi7LrCd+j4r7Zp48NLhsPzcDzYRt+2MHMmz1vmWKicANAuHiK9agCd4QDOvwIDAQAB
#  notifyUrl: http://localhost:8088/notify # 异步请求成的地址
#  returnUrl: http://localhost:8088/return # 同步请求成功之后返回的地址
#  # notifyUrl和returnUrl不能加?id=123这类自定义参数，必须外网可以正常访问